apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "vijainaks"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "vijainaks"
    spec:
      containers:
        - name: "vijainaks"
          image: "vishal.azurecr.io/vijainaks"
          ports:
          - containerPort: 3000